#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# padding
yabai -m config top_padding 8
yabai -m config bottom_padding 18
yabai -m config left_padding 18
yabai -m config right_padding 18
yabai -m config window_gap 12

yabai -m config \
    external_bar               all:55:0       \
	focus_follows_mouse off \
    window_gap                 22           \
    mouse_follows_focus        off          \
    window_zoom_persist        off          \
    window_placement           second_child \
    window_animation_duration  0.3          \
    split_ratio                0.50         \
    auto_balance               off          \
    mouse_modifier             fn           \
    mouse_action1              move         \
    mouse_action2              resize       \

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8

#when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap


# disable specific apps
yabai -m rule --add app="^Android Studio$" opacity=0.80
yabai -m rule --add app="^PyCharm$" opacity=0.80
yabai -m rule --add app="^DataSpell$" opacity=0.80
yabai -m rule --add app="^GoLand$" opacity=0.80
yabai -m rule --add app="^DataGrip$" opacity=0.80
yabai -m rule --add app="^IntelliJ IDEA$" opacity=0.80
yabai -m rule --add app="^JetBrains Rider$" opacity=0.80
yabai -m rule --add app="^Arc$" opacity=0.90
yabai -m rule --add app="^Telegram$" opacity=0.90
yabai -m rule --add app="^Discord$" opacity=0.90
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
echo "yabai configuration loaded.."
