token: y0_AgAAAABhTqdRAAG8XgAAAADP2idaaY5YogVrS2CkR_nsjYXUTeFyjv4
buffer-size-ms: 80
rewind-duration-s: 5
volume: 0.5
controls:
    quit: ctrl+q,ctrl+c
    apply: enter
    cancel: esc
    cursor-up: up
    cursor-down: down
    playlists-up: ctrl+up
    playlists-down: ctrl+down
    tracks-like: l
    tracks-share: ctrl+s
    tracks-shuffle: ctrl+x
    tracks-search: ctrl+f
    player-pause: space
    player-next: right
    player-previous: left
    player-rewind-forward: ctrl+right
    player-rewind-backward: ctrl+left
    player-like: L
