[window]
opacity = 0.3
blur = true
padding = { x = 15, y = 15 }

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }

[colors.primary]
background = "#2e0047"

[colors.cursor]
cursor = "#a605cd"
text = "#FFFFFF"

[colors.normal]
black = "#0c0c0c"
blue = "#0037da"
cyan = "#3a96dd"
green = "#FF00FF"
magenta = "#881798"
red = "#c50f1f"
white = "#cccccc"
yellow = "#c19c00"
