[colors.primary]
background = "#0a1116"
foreground = "#c1c3c4"

[colors.cursor]
text = "#0a1116"
cursor = "#c1c3c4"

[colors.vi_mode_cursor]
text = "#0a1116"
cursor = "#c1c3c4"

[colors.search.matches]
foreground = "#0a1116"
background = "#c1c3c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59656c"
background = "#c1c3c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a1116"
red = "#504645"
green = "#6E4E45"
yellow = "#914529"
blue = "#9F5529"
magenta = "#DF6711"
cyan = "#F58A0C"
white = "#c1c3c4"

[colors.bright]
black = "#59656c"
red = "#504645"
green = "#6E4E45"
yellow = "#914529"
blue = "#9F5529"
magenta = "#DF6711"
cyan = "#F58A0C"
white = "#c1c3c4"

[colors.dim]
black = "#c1c3c4"
red = "#504645"
green = "#DF6711"
yellow = "#914529"
blue = "#9F5529"
magenta = "#6E4E45"
cyan = "#F58A0C"
white = "#59656c"

[window]
opacity = 0.45
blur = true
padding = { x = 15, y = 15 }

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
